In [1]:
from scipy import integrate
from sympy import *
import numpy as np
import pandas as pd
from collections import Counter
import math


2.1

In [2]:
P = np.matrix([
    [1, -1, 0],
    [0, 1,-1],
    [2, 1, 1]])
Q = np.matrix([
    [0],
    [0],
    [1]])
lam = np.array([-1,-1,-1])

In [3]:
p = P.shape[1]
S = np.copy(P)
for i in range(p):
    S[:,i] = (P**(i)).dot(Q).T
print(S)
np.linalg.matrix_rank(S)

[[ 0  0  1]
 [ 0 -1 -2]
 [ 1  1  0]]


3

In [4]:
w,v = np.linalg.eig(P)
fi = np.poly(w)[1:]
ksi = np.poly(lam)[1:]

gam = (fi-ksi)


In [5]:
K = np.eye(p)
for i in range(1,p):
    K +=np.eye(p,k=i)*fi[i-1]

A = S.dot(K)
A = np.linalg.inv(A)
print(gam,A)

[-6.  1. -5.] [[ 1. -2.  1.]
 [ 1. -1. -0.]
 [ 1.  0.  0.]]


In [6]:
C = gam.dot(A)

In [7]:
C

array([-10.,  11.,  -6.])

3.1

In [8]:
P = np.matrix([
    [-1, 0, 0,1],
    [0, -1,1,-1],
    [1, 1, 0,0],
    [-1, 0, 0,0]])
Q = np.matrix([
    [0],
    [0],
    [1],
    [0]])
lam = np.array([-1,-2])

In [9]:
p = P.shape[1]
S = np.copy(P)
for i in range(p):
    S[:,i] = (P**(i)).dot(Q).T
print(S)
n = np.linalg.matrix_rank(S)
nn = n

[[ 0  0  0  0]
 [ 0  1 -1  2]
 [ 1  0  1 -1]
 [ 0  0  0  0]]


In [10]:
E = np.eye(p)
for i in range(n,p):
    for j in range(p):
        S[:,i] = E[:,j]
        if np.linalg.matrix_rank(S) > n:
            n+=1
            break
print(S)

[[0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]]


In [11]:
Pwave = np.linalg.inv(S)*P*S
Pwave

matrix([[ 0.,  1.,  1.,  0.],
        [ 1., -1.,  0., -1.],
        [ 0.,  0., -1.,  1.],
        [ 0.,  0., -1.,  0.]])

In [12]:
K1 = np.eye(nn)
p11 = (-1)*np.matrix([Pwave[p-nn-i-1,nn-1] for i in range(nn)])
print(p11)
for i in range(nn-1):
    K1 += np.eye(nn,k=i+1)*p11[0,i]
print(K1)

[[ 1. -1.]]
[[1. 1.]
 [0. 1.]]


In [13]:
ksi = np.poly(lam)[1:]
gam = p11-ksi
A = np.hstack([K1, np.zeros((nn,p-nn))])
B = np.hstack([np.zeros((p-nn,nn)), np.eye((p-nn))])
K = np.vstack((A,B))
print(K)
gam = np.hstack([gam, np.zeros((1,p-nn))])
print(gam)

[[1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[-2. -3.  0.  0.]]


In [14]:
C = gam*np.linalg.inv(S.dot(K))
C

matrix([[ 0., -1., -2.,  0.]])